### ISSUE TITLE
Some questions about rive UI aliasing problem and Input Change feature in Unreal plugin.

### ISSUE THREAD

**Issue by pelotyo** [rive-app/rive-unreal#100]
~~I'm sorry but this is more likely a question than an issue. 
I wonder if there is an way of using "exit" "enter" feature implemented in Rive directly in Unreal without recreating the same functionality.~~
 
Edit: I found a solution, it seems that nested widget was the problem.Even if it's included "Rive Widget" state machine made with those feature wouldn't work.

And I noticed when I imported some assets, the image get rasterized or more like blured when is in low resolution,even if I extend the resolution made with vector shape in rive it continue getting some jagged effect on edges.

I see on github front page that says, procedural rendering is coming out soon, is this coming up feature has something to resolve this aliasing issue ?

**Comment by Tod-Rive** [comment]
Hello! It's possible you're seeing a blending issue in Unreal plug-in. We're currently working on a fix for aliasing and transparency issues.

**Comment by Tod-Rive** [comment]
Hi! Version Unreal plugin [version 0.1.12](https://github.com/rive-app/rive-unreal/releases/tag/0.1.12) (released yesterday) fixes transparency and blending issues. Please give it a try!
