### ISSUE TITLE
Fatal Error after build

### ISSUE THREAD

**Issue by pelotyo** [rive-app/rive-unreal#102]
![image](https://github.com/user-attachments/assets/fb65d9be-9c6a-4ba6-86b7-979f457912d3)
I'm on version 5.4 and is it capable to build things using rive ? How I could prevent this problem?

**Comment by Tod-Rive** [comment]
Hello! Rive doesn't officially support 5.4 just yet, but we've been running internal tests that show no issue so far. Are you using the latest Unreal plugin ([0.1.11](https://github.com/rive-app/rive-unreal/releases/tag/0.1.11))?
