### ISSUE TITLE
Android Packaging broken

### ISSUE THREAD

**Issue by ItS-a-Biene** [rive-app/rive-unreal#115]
Since 0.2.0, Android builds with Rive fail in UE 5.4. Windows packaging still works.
I get errors from RiveRenderTarget.cpp, stating that "RenderContext" does not exist.

Edit: after building with 0.1.14, packaging succeeds, but the Rive widgets are not working on the packaged build on my android device. The same project and .riv file already worked fine on the android device, so I am not sure where this problem comes from now.

**Comment by Tod-Rive** [comment]
Hello, if this is still an issue please file a ticket at our [portal](https://rive.atlassian.net/servicedesk/customer/portal/3/group/4/create/35).
