### ISSUE TITLE
Build failed with critical errors

### ISSUE THREAD

**Issue by elai950** [rive-app/rive-unreal#118]
I downloaded this git, unzipped and placed the plugin in my project's `Plugins/` folder.
Tried to build the project (using Rider) and it is failing with this errors:

```c++
0>------ Building 4 action(s) started ------
0>[1/4] Link [x64] UnrealEditor-RiveRenderer.dll
0>rive_libwebp.lib: Error  : LNK1107: invalid or corrupt file: cannot read at 0x84
0>[2/4] Link [x64] UnrealEditor-RiveEditor.dll
0>rive_libwebp.lib: Error  : LNK1107: invalid or corrupt file: cannot read at 0x84
0>[3/4] Link [x64] UnrealEditor-Rive.dll
0>rive_libwebp.lib: Error  : LNK1107: invalid or corrupt file: cannot read at 0x84
```

Any help?

UE 5.4
Windows 11 64 bit

**Comment by Tod-Rive** [comment]
Once you've placed the plugin in the Plugins/Rive/ folder, start the Unreal editor. It will detect and build the plugin.

**Comment by elai950** [comment]
I did exactly that but then I got an error says : "Try rebuilding from source manually."
When I build using Rider it shows the errors above.

**Comment by elai950** [comment]
I created a brand new project and same results.

**Comment by elai950** [comment]
@Tod-Rive 
So stupid of me.
I downloaded the library using "Download Zip" instead of downlading the plugin from the release page.
It works now!
Thanks for the help BTW

**Comment by Tod-Rive** [comment]
Happy to hear it! Thanks for letting us know.
