### ISSUE TITLE
Binaries and Intermediate folder should not be included

### ISSUE THREAD

**Issue by linqen** [rive-app/rive-unreal#120]
Hey, this is more as a feedback rather than an issue.

Binaries and Intermediate folder should not be included when you upload a tag with a ZIP of the plugin's files.

Those folders are generated by the compilation and IDE during development, and will be regenerated in other devs computers.

**Comment by Tod-Rive** [comment]
Agreed. We're currently working on automating our release process and will clean this up. Thanks for the feedback.
