### ISSUE TITLE
Using the 0.2.2 download from Releases - build only works for 5.4 what 5.2.x or 5.3.x?

### ISSUE THREAD

**Issue by liquidscorpio** [rive-app/rive-unreal#121]
![image](https://github.com/user-attachments/assets/4090b00d-25df-4ac8-8cdf-a380aa321125)

**Comment by Tod-Rive** [comment]
Hello! Go ahead and select "yes", the plugin should work fine in 5.3.

**Comment by Tod-Rive** [comment]
And now we've released 0.2.4. Please give it a try. I'll close this but feel free to report again if you have issues.
