### ISSUE TITLE
Game crashes on start

### ISSUE THREAD

**Issue by Tmills-work** [rive-app/rive-unreal#122]
We ran into an issue after packaging the game.
When launching the game we get this message. 
![PackageError](https://github.com/user-attachments/assets/af74b1e9-aa44-4044-a645-7c9d1b6c9feb)

**Comment by Tod-Rive** [comment]
Hello. What version of Unreal and Rive are you using?

**Comment by Tmills-work** [comment]
Hey. We are using UE5.4.3 and plugin version 0.2.2

**Comment by Tod-Rive** [comment]
What platform are you building for?

**Comment by Tmills-work** [comment]
Windows for now, but we would like to run on platforms when it becomes available.

**Comment by Tmills-work** [comment]
Just adding an update. This only happens if I turn on the RHI Technical preview. We also have DirectX 12 on with SM6

**Comment by Tmills-work** [comment]
I see the issue. It's stashed on the blog page.
https://rive.app/blog/rive-x-unreal-rhi-technical-preview

![image](https://github.com/user-attachments/assets/aaefceb8-d71a-4684-9be9-6fc41317c4b8)

**Comment by Tod-Rive** [comment]
Right. Interestingly, I'm able to package fine on my dev machine. So we're getting there.

**Comment by Tmills-work** [comment]
Haha. Should I keep trying or just wait for the v 0.2.3 release?

**Comment by Tod-Rive** [comment]
For now, wait for a later version before trying to package with RHI.

**Comment by Tmills-work** [comment]
Sounds good! thank you!
