### ISSUE TITLE
Rive does not package

### ISSUE THREAD

**Issue by Iceisn1ce** [rive-app/rive-unreal#123]
Using UE 5.4 + Rive 0.2.2 

Rive does not package for Windows, other plugins do withoutn a problem. 
Error when starting the packaged project:

Plugin 'Rive' failed to load because module 'Rive' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.

**Comment by Tod-Rive** [comment]
Hi,

1. Are you trying to package using the experimental Rive RHI feature?
2. Did the Rive plugin build correctly when you first installed/copied it to your project?
3. Have you tried regenerating the Visual Studio project files by right-clicking on the .uproject file?

**Comment by Iceisn1ce** [comment]
1. Tested it with and without the RHI feature
2. Yes, it works
3. No, because it is a blueprint only project. Do I need a c++ project to package?

**Comment by Tod-Rive** [comment]
That's a good question. Strictly speaking you shouldn't need a c++ project, but I've found it helpful when Unreal gets a little finicky. It can help get out of strange compiling stalemates. Go ahead and add c++ class from Tools/New c++ class.

Where did you place the plugin? It should be located in YourProject/Plugins/Rive/

**Comment by Tod-Rive** [comment]
Since I haven't heard back in a while, I'll close this out. Please let me know if you still have issues. You may want to give our [latest release](https://github.com/rive-app/rive-unreal/releases/tag/0.2.4) a try.
