### ISSUE TITLE
Not able to build the plugin in Unreal 5.3.2 in Visual Studio 2022

### ISSUE THREAD

**Issue by bubble8773** [rive-app/rive-unreal#124]
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2614	'RenderBufferRHIImpl': illegal member initialization: 'lite_rtti_override' is not a base or member	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	289	
Error	C3861	'flags': identifier not found	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	310	
Error	C2660	'FRHICommandList::DrawIndexedPrimitive': function does not take 6 arguments	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	1651	
Error	C2065	'GRHISupportsRasterOrderViews': undeclared identifier	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	187	
Error	C2504	'LITE_RTTI_OVERRIDE': base class undefined	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.hpp	114	
Error	C2039	'LITE_RTTI_OVERRIDE': is not a member of 'rive'	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.hpp	114	
Error	C3668	'RenderBufferRHIImpl::onMap': method with override specifier 'override' did not override any base class methods	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.hpp	124	
Error	C3668	'RenderBufferRHIImpl::onUnmap': method with override specifier 'override' did not override any base class methods	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.hpp	125	
Error	C2440	'return': cannot convert from 'rive::rcp<RenderBufferRHIImpl>' to 'rive::rcp<rive::RenderBuffer>'	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	941	
Error	C3861	'sizeInBytes': identifier not found	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	315	
Error	C2039	'sizeInBytes': is not a member of 'RenderBufferRHIImpl'	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	1654	
Error	C3861	'SwizzleRiveColorToRGBAPremul': identifier not found	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	1288	
Error	C2039	'SwizzleRiveColorToRGBAPremul': is not a member of 'rive::gpu'	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.cpp	1288	
Error	C2143	syntax error: missing ',' before '('	RiveTest	D:\Unreal Projects2\RiveTest\Plugins\rive-unreal-main\Source\RiveRenderer\Private\Platform\RenderContextRHIImpl.hpp	114	
Error	MSB3073	The command ""C:\Program Files\Epic Games\UE_5.3\Engine\Build\BatchFiles\Rebuild.bat" RiveTestEditor Win64 Development -Project="D:\Unreal Projects2\RiveTest\RiveTest.uproject" -WaitMutex -FromMsBuild" exited with code -1.	RiveTest	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets	50	
`

**Comment by Tod-Rive** [comment]
1. What version of the Rive plugin are you using?
2. This looks like a potential version mismatch in the files. Are you trying to upgrade an older version of the plugin? Or is this a new install? If you're upgrading, be sure to completely delete the older plugin before copying in the newer.

**Comment by bubble8773** [comment]
I am trying to 0.2.2 version and this is my new install

**Comment by Tod-Rive** [comment]
The plugin should be automatically when you run the Unreal Editor. Where are you getting the output you've pasted?

**Comment by bubble8773** [comment]
I am getting this  in Visual studio 2022  when I tried to build a C++ project that I created using Unreal Engine 5.4

**Comment by Tod-Rive** [comment]
Did you see the plugin build when you started unreal?

**Comment by Tod-Rive** [comment]
Ok, we're working on a new release that, if you can, would probably make sense for you to wait for. Let me know if this is more time critical and we can continue working through the issue you're seeing.

**Comment by Tod-Rive** [comment]
We've released 0.2.3. Please try that release.

**Comment by BubblesNew** [comment]
Hello Tod, Thank you for you help. I tried the latest version and now I am able to enable the plugin and open the project

**Comment by Tod-Rive** [comment]
Glad it worked! Sorry for the trouble.
