### ISSUE TITLE
Using Rive for UI works great in-editor but not in packaged build.

### ISSUE THREAD

**Issue by rwinright** [rive-app/rive-unreal#126]
Widgets that are loaded with my UI at the time the application starts look fine but ones that I instantiate in-game or set visible from a collapsed or hidden are extremely blurry and/or pixelated. It's almost as if they're being rendered too small and scaled up into their containers. This is inconsistent because the widgets clear, load, and swap visibility just fine in-editor. 

I have noticed that if I have the widgets visible for at least 1 second on-screen and then set them hidden, then set them back to visible, I don't have this problem... but that's not really a feasible solution for my project as I cannot render every single widget that I need visible at the start. 

Using Unreal Engine 5.4
Rive for Unreal 0.2.2

I've tried resizing, disabling texture streaming, setting the filters on the rive textures (although, I don't think that does anything), changing the anchors and other settings at runtime when instantiated. 

This is in PIE mode. The icons at the top of the editor are static and instantiate at load
![image](https://github.com/user-attachments/assets/3dafe898-4083-4f24-89f5-8c288aa78956)

This is in a packaged game: 
![image](https://github.com/user-attachments/assets/62ec667d-2be2-4673-bcc4-88726a27d2a9)

**Comment by Tod-Rive** [comment]
Hello, this certainly doesn't look right. Are you instantiating via code or blueprints?

**Comment by rwinright** [comment]
> Hello, this certainly doesn't look right. Are you instantiating via code or blueprints?

Hello Tod! I'm instantiating these via blueprints!

**Comment by rwinright** [comment]
I'll absolutely do so! 
I tested in another project as well and have the same results, so I believe you won't have any problem. 

Basically any place where you just instantiate it with Create Widget + Add to Viewport or have it set to hidden/collapsed of any sort at the start will make it a pixelated granulated mess. I'll send that through in just a moment. Thank you!

**Comment by Tod-Rive** [comment]
I'm not seeing the same behavior. I'm using the newly released 0.2.3 so you might want to give that a try.

**Comment by Tod-Rive** [comment]
I'm going to close this out since I haven't heard back in a while. Feel free to file a ticket if you're still seeing the issue and we'll help in any way we can (note that we're out for the holidays). Also, we just [released 0.2.4](https://github.com/rive-app/rive-unreal/releases/tag/0.2.4) so you may want to give that a try.
