### ISSUE TITLE
[QUESTION] Does this support console's, VR/AR, and mobile?

### ISSUE THREAD

**Issue by YawLighthouse** [rive-app/rive-unreal#48]
Hello I haven't been able to find this information online(may be something to notify the documentation team about). Has this been tested on consoles, mobile, and VR/AR platforms. If it does not support them then it may be good to list those platforms supported/not supported for this plugin which may be a deciding factor for developers interested in using this plugin.

**Comment by Batname** [comment]
IOS and Android (OpenGL) - yes

We have plans for Linux/Vulcan; after that, you can run on devices like Steam Deck.

Theoretically, it might work on Apple Vision Pro, but we never tested
Theoretically, it might work on Oculus Quest (Andorid|OpenGL), but we never tested it yet

We'll add DX12 support, and after that, we will test on the Xbox.
PS5 this is point of investigation
