### ISSUE TITLE
Unspecified Function

### ISSUE THREAD

**Issue by peteshand** [rive-app/rive-unreal#52]
Hey
Any idea why i would be getting unspecified function?
I've created a new ue5.3 projected, added the Rive plugin and opened the '/Rive/Materials/M_UnlitText.M_UnlitText'

![unspecified_function](https://github.com/rive-app/rive-unreal/assets/139457/d574623d-5d93-4ca7-b188-7b02e4a49cb7)

**Comment by peteshand** [comment]
issue also present in the rive-unreal-example project
`https://github.com/rive-app/rive-unreal/releases`

**Comment by Voulz** [comment]
Thank you @peteshand for finding this.
I am not sure what these functions are but you can just delete those and the material will still work.
We'll fix it on our end.
![image](https://github.com/rive-app/rive-unreal/assets/12561988/ee2a2d3b-7c36-4766-9592-ba7bc3c8d723)
