### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by Reec-3** [rive-app/rive-unreal#55]
When using transparency with no background colour the resulting image in UE5 is incorrect. I've tried all blend modes, the only one that kind of works is translucent but this makes the whole thing too light and doesn't look like the original art in Rive Editor.

To reproduce, make the artboard background transparent, then make something like a rectangle with a gradient that blends from a solid colour to transparent.

Update: NoesisGUI renders the same RiveFile correctly.

**Comment by Reec-3** [comment]
Here are some visuals to show what I mean. Three rectangles from left to right, 50% alpha, linear gradient from top to bottom (100-0% alpha), and radial gradient.

The original
![Original](https://github.com/rive-app/rive-unreal/assets/31294558/9715d607-3e8f-4ebd-8833-99cb0bc7e103)

Alpha blend as it shows in the RiveFile
![AlphaBlend](https://github.com/rive-app/rive-unreal/assets/31294558/1f5d4e6d-d471-44c9-ba04-4836b66a96a1)

Alpha blend as it shows in game
![AlphaBlendInGame](https://github.com/rive-app/rive-unreal/assets/31294558/595a8294-1a3d-4dfc-9635-9674f4995d3c)

Opaque as it shows in the RiveFile
![Opaque](https://github.com/rive-app/rive-unreal/assets/31294558/cc988e6c-f75c-4a2c-9010-f730c45a0c93)

Opaque as it shows in game
![OpaqueInGame](https://github.com/rive-app/rive-unreal/assets/31294558/d62e9bd1-f0b6-400c-8f48-69d5912621ca)

Translucent as it shows in the RiveFile
![Translucent](https://github.com/rive-app/rive-unreal/assets/31294558/21c02c70-bc65-40d5-b97d-d9f82a624863)

Translucent as it shows in game (against a dark background so you can see it easier)
![TranslucentInGame](https://github.com/rive-app/rive-unreal/assets/31294558/fc93a870-9adc-426d-bd16-b4fee6fddaa2)

As you can see translucent is the closest to the original but some detail appears to be lost. Also when the blend mode is set to translucent it does not render in widget components regardless of material.

**Comment by Voulz** [comment]
Thank you @Reec-3 for the detailed information, we are working on this. There are a few issues with transparency linked to DX11 that we are looking at

**Comment by LucasNova** [comment]
Maybe it also related to that issue, radial gradient and gradients works wrong in unreal, for example what we have in rive app
![image](https://github.com/rive-app/rive-unreal/assets/8263974/728092e7-b541-4bc0-8dac-fa8023e4f14c)

And what we have in Unreal:
![image](https://github.com/rive-app/rive-unreal/assets/8263974/c353dafe-0e20-45af-9fe8-40118abda036)

**Comment by Voulz** [comment]
@Reec-3 and @LucasNova , the DirectX11 issues should have been fixed now in both development and main branches. Let me know if you still have issues.
![image](https://github.com/rive-app/rive-unreal/assets/12561988/8b0b4658-7bbf-49d5-b2b4-9a7d7490f1e8)

**Comment by LucasNova** [comment]
@Reec-3, For me at the 0.1.4 all fine. Thanks a lot.
