### ISSUE TITLE
RiveRenderer is null

### ISSUE THREAD

**Issue by MushroomKiller** [rive-app/rive-unreal#56]
New project with Rive plugin only, cannot create Rive File asset, neither via drag'n'drop or context menu in content browser. Output log shows following:

LogRiveEditor: Error: RiveRenderer is null, unable to import the Rive file _%my filepath%_
or
LogRiveEditor: Error: RiveRenderer is null, unable to create and instance of the Rive file 'None'

Engine version is 5.3.2

**Comment by Voulz** [comment]
Hi, it sounds like you are on an unsupported RHI. Could you check your Output window for warnings and errors? On Windows, we currently only support DirectX 11.
We are also planning to add a notification to make this clearer in the future.

**Comment by MushroomKiller** [comment]
Got it, thank you. Working _almost_ perfectly with DX11, but have some issues with moving gradients (showing as flat color).
It's sad that this is the only DX11 supported, I'll wait for DX12 support
