### ISSUE TITLE
Is there a plan to support the Unreal DX12 RHI?

### ISSUE THREAD

**Issue by delscorcho** [rive-app/rive-unreal#57]
Hi, we'd like to consider using Rive, but we're limited to the DX12 RHI in Unreal due to some key aspects of Lumen/Nanite only being compatible with DX12. 

Do you have plans to support the DX12 RHI?

**Comment by Voulz** [comment]
Hi @delscorcho, there is planned support for DX12 that the team is actively working on. We'll integrate to the UE plugin once ready

**Comment by delscorcho** [comment]
Sounds good, thanks!
