### ISSUE TITLE
unable to open project after moving plugin file to plugins folder

### ISSUE THREAD

**Issue by lorenzoromagnoli** [rive-app/rive-unreal#78]
After moving the Rive plugin to the project folder, I get a compilation error when trying to open the project. 
![Screenshot 2024-04-09 162156](https://github.com/rive-app/rive-unreal/assets/2944758/158a8fcd-4f85-4616-9741-4ebc84200eb6)

Recompiling doesn't work
![Screenshot 2024-04-09 162210](https://github.com/rive-app/rive-unreal/assets/2944758/ab388b69-4807-4f6a-b09f-074d7d6a753d)

Running Unity engine 5.3.2 on windows. 
When opening any of the examples I get the same error.

**Comment by lorenzoromagnoli** [comment]
I figured I was missing all the dependencies needed for unreal to recompile the plugin for my architecture. it seems to be working now.

**Comment by tomroohan** [comment]
I'm having the same issue with this message appearing - This is for a new project file. 
<img width="358" alt="Screenshot 2024-04-14 at 12 48 55 PM" src="https://github.com/rive-app/rive-unreal/assets/164459551/8811f83d-b013-4aa8-852a-b638ef8d7886">
