### ISSUE TITLE
Missing Modules Error - new project

### ISSUE THREAD

**Issue by tomroohan** [rive-app/rive-unreal#80]
<img width="358" alt="Screenshot 2024-04-14 at 12 48 55 PM" src="https://github.com/rive-app/rive-unreal/assets/164459551/3eee36be-21eb-4692-b264-73a85446e9f7">

I get this message when I copy the plugin folder into the engine plugin directory. Using UE5.3.2 ARM64

**Comment by Voulz** [comment]
Hi @tomroohan, currently you need to rebuild the plugin manually as it is not yet distributed through the Marketplace.
You will need to have XCode and rebuild your Unreal Engine project (and therefore the Rive Plugin) from XCode, and it should then work for this project.

**Comment by jameslashmar** [comment]
Anyone else landing here from Windows, here is the rebuilt 0.2.6 plugin for Windows and Unreal 5.3.2
https://www.dropbox.com/t/w9gd72NDNhjPXchh
