### ISSUE TITLE
The following modules are missing or built with a different engine version:

### ISSUE THREAD

**Issue by Skyprex** [rive-app/rive-unreal#93]
"The following modules are missing or built with a different engine version:

  Rive
  RiveRenderer
  RiveEditor
  RiveCore

Engine modules cannot be compiled at runtime. Please build through your IDE."

I have tried it with UE5.3 and UE5.4 and the error message appears with both versions.

![Screenshot 2024-06-03 003354](https://github.com/rive-app/rive-unreal/assets/67590567/ac742a32-a550-4289-9167-ae7928855fad)

**Comment by Voulz** [comment]
Hi @Skyprex, as the message says, you need to build the project with the plugin from Visual Studio (or another IDE) to get started. We are currently only providing the code, so it needs to be compiled on your machine.
