### ISSUE TITLE
Error LNK1107 & MLB3073

### ISSUE THREAD

**Issue by alexandrefLetsPlayCloud** [rive-app/rive-unreal#96]
Hello everyone, i have a small problem here. When i want to generate my project with my IDE. I have some errors. 

LNK1107 : invalid or damaged file: cannot read at 0x83

I'm on Unreal Engine 4.27 ( so yes , i used the branch 4.27-dev of this github )

Can you help me please ? 
have a good dday 
![image](https://github.com/rive-app/rive-unreal/assets/76774341/4aa5b916-8382-4ff8-a661-ee45f8b5825d)

**Comment by Voulz** [comment]
Hi @alexandrefLetsPlayCloud, could you check that you are using Git LFS?
Otherwise, can you check the file size and content of the `rive_sheenbidi.lib` on your machine? That might help us understand the issue

**Comment by alexandrefLetsPlayCloud** [comment]
oh , no i dont have git LFS. Could this be the reason for the errors when I want to build my project with the Rive plugin? I'll test it later today.

**Comment by alexandrefLetsPlayCloud** [comment]
I installed Git LFS, but no change, and my rive_sheenbidi.lib file weighs 131 bytes. Here's what's in the file. 
![image](https://github.com/rive-app/rive-unreal/assets/76774341/3484d92c-4cac-4549-9108-6bf4ad85f9da)

**Comment by alexandrefLetsPlayCloud** [comment]
I confirm there has been a change haha. I did a new installation this time using git LFS, and I don't get the same errors anymore. 

![image](https://github.com/rive-app/rive-unreal/assets/76774341/fa004803-fb83-4268-a125-722af45c488a)
